### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by webserveis** [MasayukiSuda/CountAnimationTextView#1]
Add posibility change steps frequency +1 and speed with animations, ease etc...

**Comment by MasayukiSuda** [comment]
speed with animations use setInterpolator.
```
    mCountAnimationTextView
        .setInterpolator(new AccelerateInterpolator())
        .countAnimation(0, 9999999);
```

Add Kind of easing , please refer to <a href="https://github.com/MasayukiSuda/EasingInterpolator">this library</a> .
